[package]
name = "tether-egui"
version = "0.1.0"
edition = "2021"


[dependencies]
egui = "0.21.0"
eframe = "0.21.3"
env_logger = "0.10"
tether-agent = "0.2.3"
serde = { version = "1.0", features = ["derive"] }
